name: Deploy React Application

on:
  push:
    branches:
      - main

env:
  AWS_S3_BUCKET: s3-aws-frontend-test
  SOURCE_DIR: './dist'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4 # Clona el repositorio

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm install # Instala las dependencias del proyecto

      - name: Create .env.production
        run: echo "VITE_API_URL_NOTES=${{ vars.VITE_API_URL_NOTES }}" > .env.production

      - name: Build project
        run: npm run build # Genera los archivos en la carpeta dist/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync files to S3
        run: |
            aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}/ --delete
      
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
